#!/bin/sh

PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/scripts/functions
. /usr/share/initramfs-tools/hook-functions

for file in /usr/lib/firmware/rtl_bt/*; do
    if [ -f "${file}" ]; then
        copy_exec "${file}" /usr/lib/firmware/rtl_bt
    fi
done

exit 0
