name: Build OrangePi Image

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        board: [orangepi5] #, orangepi5b, orangepi5plus, rock5a, rock5b, nanopir6c, nanopir6s, indiedroid-nova

    runs-on: buildjet-8vcpu-ubuntu-2204-arm
    env:
      BOARD: ${{ matrix.board }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache build directory
        uses: actions/cache@v2
        with:
          path: ./build
          key: ${{ runner.os }}-build-${{ github.sha }}-${{ env.BOARD }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}-${{ env.BOARD }}
            ${{ runner.os }}-build-${{ github.sha }}-
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf bc git wget make libc6-dev libncurses5-dev libncursesw5-dev libssl-dev flex bison
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu bison qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted udev dosfstools uuid-runtime git-lfs device-tree-compiler python2 python3 python-is-python3 fdisk

      - name: Build Kernel for ${{ matrix.board }}
        run: |
          sudo ./build.sh -b ${{ matrix.board }} -k

      - name: Run debug scripts
        run: |
          pwd || true
          ls -alh || true
          ls -alh build || true
          ls -alh images || true

      - name: Build Uboot for ${{ matrix.board }}
        run: |
          sudo ./build.sh -b ${{ matrix.board }} -u

      - name: Run debug scripts
        run: |
          pwd
          ls -alh
          ls -alh build
          ls -alh images || true


      - name: Run build script
        run: |
          sudo ./build.sh -b ${{ matrix.board }}

      - name: Run debug scripts
        run: |
          pwd
          ls -alh
          ls -alh build
          ls -alh images

      - name: Upload server image
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.board }}-server-image
          path: ./images/ubuntu-22.04.2-preinstalled-server-arm64-${{ matrix.board }}.img.xz

      - name: Upload desktop image
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.board }}-desktop-image
          path: ./images/ubuntu-22.04.2-preinstalled-desktop-arm64-${{ matrix.board }}.img.xz
