name: Build Ubuntu 22.04 Image

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: choice
        description: Board 
        options: 
        -
        - orangepi-5
        - orangepi-5b
        - orangepi-5-plus
        - rock-5b
        - rock-5a
        - radxa-cm5-io
        - nanopc-t6
        - nanopi-r6c
        - nanopi-r6s
        - indiedroid-nova
        - mixtile-blade3
        - lubancat-4

jobs:
  build:
    strategy:
      matrix:
        board: ["${{ github.event.inputs.name }}"]

    runs-on: ubuntu-latest

    env:
      BOARD: ${{ matrix.board }}

    steps:
      - name: Get More Disk Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: Joshua-Riek/ubuntu-rockchip

      - name: Checkout LFS
        run: |
          git lfs fetch
          git lfs checkout

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu bison \
          qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support \
          debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted \
          udev dosfstools uuid-runtime git-lfs device-tree-compiler python2 python3 \
          python-is-python3 fdisk bc

      - name: Run Build Script
        run: |
          sudo ./build.sh -b ${{ matrix.board }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-22.04.3-preinstalled-arm64-${{ matrix.board }}
          path: ./images/ubuntu-22.04.3-preinstalled-*-arm64-${{ matrix.board }}.*
